### ISSUE TITLE
Is this code able to reproduce the amazing images in your paper?

### ISSUE THREAD

**Issue by mscipio** [mikgroup/extreme_mri#2]
Hi! Thanks a lot for sharing your code, and congratulation for the amazing work described in your recent paper!

I was looking at the colab notebook, and it seems to me that there are some simplifications there with the final results not really approaching what we can see in the paper. Is there an "easy" way to change the notebook to reproduce your result for the pedriatic dce-mri dataset, or what you shared is just a simpler example?

Thanks!

**Comment by frankong** [comment]
Yes, the simplest way would be to comment out `
(Optional) Speed up reconstruction by cropping k-space` part, and also set the number of frames `T` to 500 instead of 100.

It'll probably take a long time to run on colab. If you have a more powerful GPU on your own server, I recommend running the example offline.

**Comment by mscipio** [comment]
Thanks a lot, I will try that!
Any chance you remember the resampling factor you used to plot the reconstructed volume across coronal and sagittal planes? I mean, to take into account the different resolution along the z-axes ...

it is a trivial question, but I'd really like to reproduce something similar to the video you submitted as supplementary, to be sure everything works fine with your dataset, before starting figuring out how to adapt it to my own data.
Thanks

**Comment by frankong** [comment]
The resolution is 1×1×1.8mm3, so I stretch the slice dimension by 1.8 for visualization
